# =============================================================================
# CELL 5: 3D Feasible Space Manifold (Molzahn 2017, Figure 3 Replication)
# =============================================================================
import os
import pickle
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# 1. Load the dataset generated by your HPC parameter sweep
input_filename = "wb5_feasible_points_FINAL_53185.pkl"
if not os.path.exists(input_filename):
    raise FileNotFoundError(f"Could not find '{input_filename}'. Ensure it is in your notebook folder!")

with open(input_filename, "rb") as f:
    plot_points = pickle.load(f)

print(f"✔ Successfully loaded {len(plot_points):,} feasible points.")

# 2. Extract projection axes: P_G5 (X-axis), P_G1 (Y-axis), Q_G5 (Z-axis)
P_G1_vals = np.array([pt['P_gen'][0] for pt in plot_points])  # Slack bus active generation
P_G5_vals = np.array([pt['P_gen'][4] for pt in plot_points])  # Bus 5 active generation
Q_G5_vals = np.array([pt['Q_gen'][4] for pt in plot_points])  # Bus 5 reactive generation
cost_vals = np.array([pt['cost'] for pt in plot_points])      # Objective cost ($/h)

# Clean any potential NaN/Inf values
valid_mask = ~np.isnan(cost_vals) & ~np.isinf(cost_vals)
P_G1_vals, P_G5_vals, Q_G5_vals, cost_vals = P_G1_vals[valid_mask], P_G5_vals[valid_mask], Q_G5_vals[valid_mask], cost_vals[valid_mask]

# 3. Initialize 3D Figure
fig = plt.figure(figsize=(13, 10), dpi=150)
ax = fig.add_subplot(111, projection='3d')
ax.computed_zorder = False
ax.grid(True, linestyle='--', alpha=0.5)

# 4. Plot the Continuous Feasible Manifold (Split into Above/Below for True 3D Slicing)
vmin_cost = np.percentile(cost_vals, 5)
vmax_cost = np.percentile(cost_vals, 95)

# Extract the minimum voltage magnitude across ALL buses for each point
min_v_per_point = np.array([np.min(pt['V_mag']) for pt in plot_points])

# --- CRITICAL TOPOLOGICAL SLICING ---
# 1. Below Mask: Captures any points submerged below the reactive floor
below_mask = Q_G5_vals <= -0.30

# 2. Above Mask: Keeps points above the Q plane AND filters out the middle bridge
# Using 0.935 pu removes the sagging valley points that create the artificial bridge,
# while safely preserving the full height of both operational horns!
above_mask = (Q_G5_vals > -0.30) & (min_v_per_point >= 0.935)
# ------------------------------------

# Layer 1: Submerged bottom belly (drawn UNDER the gray plane)
ax.scatter(P_G1_vals[below_mask], P_G5_vals[below_mask], Q_G5_vals[below_mask], 
           c=cost_vals[below_mask], cmap='YlOrRd', 
           s=12, alpha=0.35, edgecolors='none', 
           vmin=vmin_cost, vmax=vmax_cost, zorder=1)

# Layer 2: Separating Hyperplane at Q_G5 = -0.30 pu (drawn OVER the bottom belly)
xx, yy = np.meshgrid(np.linspace(0.5, 3.5, 10), np.linspace(-1, 2.5, 10))
zz = -0.3 * np.ones_like(xx)
ax.plot_surface(xx, yy, zz, color='lightgray', alpha=1, rstride=1, cstride=1, edgecolor='none', zorder=2)

# Layer 3: Disconnected feasible components above the limit (replicates Figure 3!)
sc = ax.scatter(P_G1_vals[above_mask], P_G5_vals[above_mask], Q_G5_vals[above_mask], 
                c=cost_vals[above_mask], cmap='YlOrRd', 
                s=12, alpha=0.85, edgecolors='none', 
                vmin=vmin_cost, vmax=vmax_cost, zorder=3)

# =============================================================================
# 6. Dynamically Extract and Highlight Optima from Computed Dataset (Layer 4)
# =============================================================================

# 1. Filter for strictly feasible points floating ABOVE the gray plane (Layer 3 space)
feasible_above = [pt for pt in plot_points if pt['Q_gen'][4] >= -0.30 and min(pt['V_mag']) >= 0.935]

# 2. Extract exact Global Optimum (Absolute minimum cost on the left horn)
global_opt = min(feasible_above, key=lambda pt: pt['cost'])
g_P1 = global_opt['P_gen'][0]
g_P5 = global_opt['P_gen'][4]
g_Q5 = global_opt['Q_gen'][4]
g_cost = global_opt['cost']

# 3. Extract exact Local Optimum (Minimum cost on the right horn where P_G5 is near 1.0 pu)
local_candidates = [pt for pt in feasible_above if 0.7 <= pt['P_gen'][4] <= 1.3]
if local_candidates:
    local_opt = min(local_candidates, key=lambda pt: pt['cost'])
    l_P1 = local_opt['P_gen'][0]
    l_P5 = local_opt['P_gen'][4]
    l_Q5 = local_opt['Q_gen'][4]
    l_cost = local_opt['cost']
else:
    # Fallback to benchmark values if candidate filter is empty
    l_P1, l_P5, l_Q5, l_cost = 2.46, 0.98, -0.30, 1112.45

print("\n--- EXACT DATASET OPTIMA VERIFIED ---")
print(f"★ Global Optimal: P_G1 = {g_P1:.4f}, P_G5 = {g_P5:.4f}, Q_G5 = {g_Q5:.4f} | Cost: ${g_cost:.2f}/h")
print(f"▲ Local Optimal:  P_G1 = {l_P1:.4f}, P_G5 = {l_P5:.4f}, Q_G5 = {l_Q5:.4f} | Cost: ${l_cost:.2f}/h")

# 4. Plot Markers (Pass coordinates in order: X=P_G1, Y=P_G5, Z=Q_G5)
ax.scatter([g_P1], [g_P5], [g_Q5], color='lime', s=350, marker='*', 
           edgecolors='black', linewidths=1.2, zorder=100, depthshade=False, 
           label=f'Global Optimal (${g_cost:.1f}/h)')

ax.scatter([l_P1], [l_P5], [l_Q5], color='cyan', s=160, marker='^', 
           edgecolors='black', linewidths=1.2, zorder=100, depthshade=False, 
           label=f'Local Optimal (${l_cost:.1f}/h)')

# 7. Axes formatting and labels
cb = plt.colorbar(sc, ax=ax, shrink=0.60, pad=0.01, aspect=25)
cb.set_label('Total Generation Cost ($/h)', fontsize=12, labelpad=10)

ax.set_xlabel('$P_{G1}$ (per unit)', fontsize=12, labelpad=12)
ax.set_ylabel('$P_{G5}$ (per unit)', fontsize=12, labelpad=12)
ax.set_zlabel('$Q_{G5}$ (per unit)', fontsize=12, labelpad=4)

# --- CRITICAL AXIS SWAP ADJUSTMENTS ---
ax.xaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))  
ax.yaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
ax.zaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))

# Set exact viewing limits matching Figure 3
ax.set_xlim([1, 5])
ax.set_ylim([-1.0, 3.0])
ax.set_zlim([-0.60, 0.80])

# --- FORCE INTEGER TICK MARKS ON X AND Y AXES ---
ax.xaxis.set_major_locator(ticker.MaxNLocator(integer=True))
ax.yaxis.set_major_locator(ticker.MaxNLocator(integer=True))

# ax.set_title("Computed ACOPF Feasible Space of 5-bus Network"
#              f"Parametric Continuation ({len(plot_points):,} Feasible Points)"
#              , fontsize=13, pad=15)

# Adjust camera viewpoint to naturally push the PG1 wall panel backward
ax.view_init(elev=0, azim=210)
ax.legend(loc='upper left', bbox_to_anchor=(0.02, 0.88), 
          framealpha=0.9, fontsize=11, 
          labelspacing=0.4, borderaxespad=0.0, handletextpad=0.5)

plt.tight_layout(pad=0.5)

# Save publication-ready vector PDF
output_pdf = f"{input_filename}.pdf"
plt.savefig(output_pdf, format='pdf', bbox_inches='tight',pad_inches=0.1)
print(f"✔ Vector PDF saved as '{output_pdf}'!")

# plt.show()